// Uses the Nuxt-prepared flat config so auto-imports, Vue SFC parsing,
// and project-specific globals are all visible to ESLint. The artifact
// at frontend/.nuxt/eslint.config.mjs is regenerated by `nuxi prepare`
// (which runs as the frontend's postinstall) whenever Nuxt config changes.
import withNuxt from './frontend/.nuxt/eslint.config.mjs'
import prettier from 'eslint-config-prettier'

export default withNuxt()
  .append({
    ignores: [
      'node_modules/',
      '**/.nuxt/',
      '**/.output/',
      '**/dist/',
      '**/build/',
      'frontend/playwright-report/',
      'frontend/test-results/',
      'frontend/i18n/locales/*.json',
      'frontend/lighthouse-report*.json',
      'specs/**',
      '.specify/**',
    ],
  })
  .append({
    files: ['frontend/**/*.vue'],
    rules: {
      // Nuxt addresses pages/layouts by their file name (`index`, `default`),
      // and the project's component library (shadcn-vue under `components/ui/`)
      // intentionally uses single-word names per its design convention.
      'vue/multi-word-component-names': 'off',
    },
  })
  .append(prettier)
